In this notebook we will see how we can create different types of indexes using [FAISS](https://github.com/facebookresearch/faiss) library for efficient similarity search.

# Install dependencies

In [1]:
!pip install datasets
!pip install sentence_transformers
!pip install faiss-cpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.7/468.7 kB 5.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 20.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.3/134.3 kB 5.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 11.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 5.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.5/212.5 kB 7.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.5/114.5 kB 4.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.6/149.6 kB 9.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 23.5 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 3.3 MB/s eta 0:0

# Import

In [2]:
from datasets import load_dataset
from sentence_transformers import SentenceTransformer

import faiss

import pandas as pd
import numpy as np
from copy import deepcopy
from tqdm import tqdm
import time
import plotly.express as px

# Data

We are going to use a Hugging Face text dataset with 832 rows. Each row of the dataset will be encoded by a BERT model with 768 dimensions.

In [27]:
dataset = load_dataset('glue', 'ax')
sentences = list(set(dataset['test']['premise']))
print(f"Number of documents: {len(sentences)}")
sentences[:5]

Generating test split:   0%|          | 0/1104 [00:00<?, ? examples/s]

Dataset glue downloaded and prepared to /root/.cache/huggingface/datasets/glue/ax/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad. Subsequent calls will reuse this data.


  0%|          | 0/1 [00:00<?, ?it/s]

Number of documents: 832


['Threatened by habitat loss and hunting, ruffed lemurs are extinct in the wild.',
 'The entity prediction task requires predicting xxxx given the preceding text either by choosing a previously mentioned entity or deciding that this is a “new entity”.',
 'Joan knows that all speech is political speech.',
 'We propose models from a restricted space of linear functions.',
 'Damp conditions and lack of oxygen contribute to the degredation of organic remains in middens.']

In [28]:
model = SentenceTransformer('sentence-transformers/bert-base-nli-mean-tokens')

In [29]:
def embed(model, sentences):
    return model.encode(sentences)

In [30]:
embeddings = embed(model, sentences) # this function may take a while to execute
dim = embeddings.shape[1]
print(f"Dimension of embeddings: {dim}")

Dimension of embeddings: 768


# IndexFlatL2 & IndexFlatIP
Let us create *IndexFlatL2*. We can already notice that *IndexFlatL2* does not require the training phase.

**NB:** *IndexFlatIP* works in a similar way as *IndexFlatL2*, except for distances it calculates inner product (not Euclidean distance).

In [ ]:
index = faiss.IndexFlatL2(dim)
# index = faiss.IndexFlatIP
assert index.is_trained
index.add(embeddings)
print(f"Total number of documents: {index.ntotal}")

Total number of documents: 832


From now, we are going to search 3 nearest neighbours for each of our queries.

In [ ]:
k = 3
queries = ['I am reading an interesting book', 'I want to buy a car']
embedded_queries = embed(model, sentences=queries)

In [ ]:
distances, indices = index.search(embedded_queries, k)
print(f"Distances:\n{distances}\n")
print(f"Indices:\n{indices}")

Distances:
[[265.9757  272.8875  276.9157 ]
 [ 95.71779 178.98122 229.10774]]

Indices:
[[710 623 227]
 [306 194 479]]


The *search()* method returns computed distances to the found objects as well as their index positions in the data. Let us iterate over it and print the results.

In [36]:
def print_results(queries, distances, indices, sentences):
    for query, query_distances, query_indices in zip(queries, distances, indices):
        print(f"\nQuery: {query}")
        for i, (query_index, query_distance) in enumerate(zip(query_indices, query_distances), 1):
            document = sentences[query_index]
            print(f"{i}. Distance = {query_distance:.2f}. {document}")

In [ ]:
print_results(queries, distances, indices, sentences)


Query: I am reading an interesting book
1. Distance = 265.98. The book astounds as Grossman richly, deeply develops characters and portrays suffering, but his portrayal of women still suffers from a lot of the unfortunate stereotypes and moralizing that we would expect of a writer from his time.
2. Distance = 272.89. The book astounds with Grossman's rich, deep character development and portrayal of suffering, but his portrayal of women still suffers from a lot of the unfortunate stereotypes and moralizing that we would expect of a writer from his time.
3. Distance = 276.92. This article reads like satire.

Query: I want to buy a car
1. Distance = 95.72. Musk decided to offer up his personal car.
2. Distance = 178.98. Musk decided to offer up his personal Tesla roadster.
3. Distance = 229.11. I can actually see him getting into a Lincoln saying this.


# IndexIVFFlat
Let us accelerate the search procedure through **inverted file index**. For that, we are going to switch to *IndexIVFFlat* which constructs a Voronoi diagram under the hood and uses it to reduce the search scope during inference.

To declare this type of index, we need to provide a **quantinizer** that will measure the distances between centers of the regions and **nlist** parameter which defines the number of regions.

In [ ]:
nlist = 20 # number of regions (Voronoi cells)
quantizer = faiss.IndexFlatL2(dim)
index = faiss.IndexIVFFlat(quantizer, dim, nlist)

Compared to *IndexFlatL2*, this time we have to train the index before adding the embeddings to it. During training, we will be building a Voronoi diagram. After that, newly added objects will be categorized into one of the regions.

On large datasets, the training procedure may take some time.

In [ ]:
assert not index.is_trained
index.train(embeddings)

assert index.is_trained
index.add(embeddings)

print(f"Total number of documents: {index.ntotal}")

Total number of documents: 832


By default, for a new point, we search only one closest centroid to it and use all the objects inside that region as potential candidates. This way we don't check candidates from other close regions which could have potentially been true nearest neighbours. This can sometimes result in lower accuracy. To fix this, it is possible to adjust the number of searched regions. FAISS allows specifying this parameter as the **nprobe** attribute.

In [ ]:
index.nprobe = 3 # increasing the search scope to 3 regions

In [ ]:
k = 3
queries = ['I am reading an interesting book', 'I want to buy a car']
embedded_queries = embed(model, sentences=queries)

In [ ]:
distances, indices = index.search(embedded_queries, k)
print_results(queries, distances, indices, sentences)


Query: I am reading an interesting book
1. Distance = 276.92. This article reads like satire.
2. Distance = 279.86. The doctor bears some responsibility for successful care.
3. Distance = 283.93. The attorney bears some responsibility for successful care.

Query: I want to buy a car
1. Distance = 95.72. Musk decided to offer up his personal car.
2. Distance = 178.98. Musk decided to offer up his personal Tesla roadster.
3. Distance = 229.11. I can actually see him getting into a Lincoln saying this.


# IndexPQ
*IndexPQ* implements product quantization which allows compressing of initial data several times. For initialisation, *IndexPQ* requires 3 parameters:
* **dim**: number of dimensions.
* **M**: number of splits for each vector.
* **nbits**: number of bits it takes to encode a single cluster ID. This means that the number of total clusters in a single subspace will be equal to k = 2<sup>nbits</sup>.

For equal subspace dimensions splitting, the parameter d must be divisible by M.

In this case, the number of bytes required to store a single vector equals $\lceil\frac{M * nbits}{8}\rceil$. As we can see, for more efficient memory usage the value of M * nbits should be divisible by 8.

In [31]:
M = 4 # number of splits for each vector
nbits = 8 # each cluster ID is encoded by 8 bits

assert dim % M == 0
index = faiss.IndexPQ(dim, M, nbits)

In [32]:
assert not index.is_trained
index.train(embeddings)

assert index.is_trained
index.add(embeddings)

In [34]:
k = 3
queries = ['I am reading an interesting book', 'I want to buy a car']
embedded_queries = embed(model, sentences=queries)

In [37]:
distances, indices = index.search(embedded_queries, k)
print_results(queries, distances, indices, sentences)


Query: I am reading an interesting book
1. Distance = 256.84. This article reads like satire.
2. Distance = 258.87. Both doctor and patient bear some responsibility for successful care.
3. Distance = 258.87. The attorney bears some responsibility for successful care.

Query: I want to buy a car
1. Distance = 127.45. Musk decided to offer up his personal Tesla roadster.
2. Distance = 127.45. Musk decided to offer up his personal car.
3. Distance = 127.45. Musk decided to offer up his personal yacht.


# Performance comparison
We are going to measure how much time it takes to find the nearest neighbour (k = 1) for 1000 queries for described indexes for different dataset sizes. This will also allow us to see how these algorithms scale on large data.

In [72]:
dim = 100
k = 1
dataset_sizes = [int(size) for size in np.linspace(5000, 100000, 39)]

# values consist of an index class and constructor parameters that will be used to initialise an index
indexes = {
    'IndexFlatIP': (faiss.IndexFlatIP, (dim,)),
    'IndexFlatL2': (faiss.IndexFlatL2, (dim,)),
    'IndexIVFFlat': (faiss.IndexIVFFlat, (faiss.IndexFlatL2(dim), dim, 50,)), # 50 regions
    'IndexPQ': (faiss.IndexPQ, (dim, 4, 8,)) # 4 subspaces each containing 2**8 = 256 clusters
}

In [78]:
df_speed = pd.DataFrame(columns=['index_type', 'dataset_size', 'training_time', 'inference_time'], index=range(len(dataset_sizes) * len(indexes)))

i = 0
for dataset_size in tqdm(dataset_sizes):
    for index_type, index_params in indexes.items():
        dataset = np.random.randn(dataset_size, dim)
        index_class, params = index_params
        params = [deepcopy(param) for param in params]
        index = index_class(*params)

        if not index.is_trained:

            # measure training time
            start = time.time()
            index.train(dataset)
            end = time.time()
            training_time = end - start

        else:
            training_time = 0

        index.add(dataset)
        query = np.random.randn(1000, dim)

        # measure inference time
        start = time.time()
        index.search(query, k)
        end = time.time()
        inference_time = end - start

        df_speed.loc[i, 'index_type'] = index_type
        df_speed.loc[i, 'dataset_size'] = dataset_size
        df_speed.loc[i, 'training_time'] = training_time
        df_speed.loc[i, 'inference_time'] = inference_time

        i += 1

In [76]:
fig = px.line(df_speed, x='dataset_size', y='training_time', color='index_type',
              title='Training time for datasets of different sizes',
              labels=dict(dataset_size='Dataset size', training_time='Time (s)', index_type='Index'))
fig.show()

*IndexFlatL2* and *IndexFlatIP* do not require any training phase. For *IndexIVFFlat* trains very fast and scales very efficiently. *IndexPQ* requires more training time because under the hood it trains several cluster algorithms.

In [77]:
fig = px.line(df_speed, x='dataset_size', y='inference_time', color='index_type',
              title='Inference search time for datasets of different sizes',
              labels=dict(dataset_size='Dataset size', inference_time='Time (s)', index_type='Index'))
fig.show()

As we can see, *IndexFlatIP* and *IndexFlatL2* scale linearly as the dataset size increases. As expected, both algorithms have a similar performance. However, the situation is different with *IndexIVFFlat* and *IndexPQ* which search neighbours more efficiently and scale better.